// ── Purchase Orders Store ────────────────────────────

import * as db from '../db.js';

let orders = [];
let nextPoNum = 1;

export async function loadOrders() {
  orders = await db.getAll('purchaseOrders');
  orders.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));

  // Determine next PO number
  const setting = await db.getById('settings', 'nextPoNumber');
  nextPoNum = setting?.value || orders.length + 1;

  return orders;
}

export function getAllOrders() { return orders; }
export function getOrderById(id) { return orders.find(o => o.id === id); }

export function getOrdersByStatus(status) {
  return orders.filter(o => o.status === status);
}

export function getActiveOrders() {
  return orders.filter(o => ['draft', 'pending-approval', 'sent', 'partially-received'].includes(o.status));
}

function generatePoNumber() {
  const year = new Date().getFullYear();
  const num = String(nextPoNum++).padStart(4, '0');
  db.put('settings', { key: 'nextPoNumber', value: nextPoNum });
  return `PO-${year}-${num}`;
}

export async function createOrder(data) {
  const record = {
    poNumber: generatePoNumber(),
    supplierId: data.supplierId,
    status: data.status || 'draft',
    lineItems: data.lineItems || [],  // [{ materialId, quantity, unitCost, receivedQty: 0 }]
    totalCost: data.totalCost || 0,
    notes: data.notes || '',
    sentAt: null,
    expectedDelivery: data.expectedDelivery || null,
    receivedAt: null,
    approvedBy: null,
    autoGenerated: data.autoGenerated || false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
  // Calculate total
  record.totalCost = record.lineItems.reduce((sum, li) => sum + (li.quantity * (li.unitCost || 0)), 0);
  record.totalCost = Math.round(record.totalCost * 100) / 100;

  const id = await db.add('purchaseOrders', record);
  record.id = id;
  orders.unshift(record);
  return record;
}

export async function updateOrder(id, updates) {
  const item = orders.find(o => o.id === id);
  if (!item) return null;
  Object.assign(item, updates, { updatedAt: new Date().toISOString() });
  if (updates.lineItems) {
    item.totalCost = item.lineItems.reduce((sum, li) => sum + (li.quantity * (li.unitCost || 0)), 0);
    item.totalCost = Math.round(item.totalCost * 100) / 100;
  }
  await db.put('purchaseOrders', item);
  return item;
}

export async function deleteOrder(id) {
  await db.del('purchaseOrders', id);
  orders = orders.filter(o => o.id !== id);
}

export async function markSent(id) {
  return updateOrder(id, { status: 'sent', sentAt: new Date().toISOString() });
}

export async function markReceived(id, lineItems) {
  const order = orders.find(o => o.id === id);
  if (!order) return null;

  // Check if all items are fully received
  const allReceived = lineItems.every(li => li.receivedQty >= li.quantity);
  const anyReceived = lineItems.some(li => li.receivedQty > 0);

  return updateOrder(id, {
    lineItems,
    status: allReceived ? 'received' : (anyReceived ? 'partially-received' : order.status),
    receivedAt: allReceived ? new Date().toISOString() : null,
  });
}

export async function cancelOrder(id) {
  return updateOrder(id, { status: 'cancelled' });
}

// Get the status badge for display
export function getOrderStatusBadge(status) {
  const map = {
    'draft':              { cls: 'ok',            label: 'Draft' },
    'pending-approval':   { cls: 'needs-made',    label: 'Pending' },
    'sent':               { cls: 'in-production', label: 'Sent' },
    'partially-received': { cls: 'in-production', label: 'Partial' },
    'received':           { cls: 'ok',            label: 'Received' },
    'cancelled':          { cls: 'low-stock',     label: 'Cancelled' },
  };
  return map[status] || map['draft'];
}
