// ── Purchase Orders Store ────────────────────────────

import { apiList, apiCreate, apiUpdate, apiDelete, apiUpsert } from '../api-client.js';

let orders = [];
let nextPoNum = 1;

export async function loadOrders() {
  orders = await apiList('orders');
  orders.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));

  // Determine next PO number from settings
  try {
    const settings = await apiList('settings');
    const setting = settings.find(s => s.key === 'nextPoNumber');
    nextPoNum = setting?.value || orders.length + 1;
  } catch {
    nextPoNum = orders.length + 1;
  }

  return orders;
}

export function getAllOrders() { return orders; }
export function getOrderById(id) { return orders.find(o => o.id === id); }

export function getOrdersByStatus(status) {
  return orders.filter(o => o.status === status);
}

export function getActiveOrders() {
  return orders.filter(o => ['draft', 'pending-approval', 'sent', 'partially-received'].includes(o.status));
}

async function generatePoNumber() {
  const year = new Date().getFullYear();
  const num = String(nextPoNum++).padStart(4, '0');
  await apiUpsert('settings', { key: 'nextPoNumber', value: nextPoNum });
  return `PO-${year}-${num}`;
}

export async function createOrder(data) {
  const record = {
    poNumber: await generatePoNumber(),
    supplierId: data.supplierId,
    status: data.status || 'draft',
    lineItems: data.lineItems || [],  // [{ materialId, quantity, unitCost, receivedQty: 0 }]
    totalCost: data.totalCost || 0,
    notes: data.notes || '',
    sentAt: null,
    expectedDelivery: data.expectedDelivery || null,
    receivedAt: null,
    approvedBy: null,
    autoGenerated: data.autoGenerated || false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
  // Calculate total
  record.totalCost = record.lineItems.reduce((sum, li) => sum + (li.quantity * (li.unitCost || 0)), 0);
  record.totalCost = Math.round(record.totalCost * 100) / 100;

  const created = await apiCreate('orders', record);
  orders.unshift(created);
  return created;
}

export async function updateOrder(id, updates) {
  const item = orders.find(o => o.id === id);
  if (!item) return null;
  const payload = { ...updates, updatedAt: new Date().toISOString() };
  if (updates.lineItems) {
    const lineItems = updates.lineItems;
    payload.totalCost = lineItems.reduce((sum, li) => sum + (li.quantity * (li.unitCost || 0)), 0);
    payload.totalCost = Math.round(payload.totalCost * 100) / 100;
  }
  const updated = await apiUpdate('orders', id, payload);
  Object.assign(item, updated);
  return item;
}

export async function deleteOrder(id) {
  await apiDelete('orders', id);
  orders = orders.filter(o => o.id !== id);
}

export async function markSent(id) {
  return updateOrder(id, { status: 'sent', sentAt: new Date().toISOString() });
}

export async function markReceived(id, lineItems) {
  const order = orders.find(o => o.id === id);
  if (!order) return null;

  // Check if all items are fully received
  const allReceived = lineItems.every(li => li.receivedQty >= li.quantity);
  const anyReceived = lineItems.some(li => li.receivedQty > 0);

  return updateOrder(id, {
    lineItems,
    status: allReceived ? 'received' : (anyReceived ? 'partially-received' : order.status),
    receivedAt: allReceived ? new Date().toISOString() : null,
  });
}

export async function cancelOrder(id) {
  return updateOrder(id, { status: 'cancelled' });
}

// Get the status badge for display
export function getOrderStatusBadge(status) {
  const map = {
    'draft':              { cls: 'ok',            label: 'Draft' },
    'pending-approval':   { cls: 'needs-made',    label: 'Pending' },
    'sent':               { cls: 'in-production', label: 'Sent' },
    'partially-received': { cls: 'in-production', label: 'Partial' },
    'received':           { cls: 'ok',            label: 'Received' },
    'cancelled':          { cls: 'low-stock',     label: 'Cancelled' },
  };
  return map[status] || map['draft'];
}
