// ── Auto-Order Service ───────────────────────────────
// Detects low stock materials and generates purchase orders.

import { getAllMaterials } from '../stores/materials.js';
import { getAllSuppliers } from '../stores/suppliers.js';
import { getActiveOrders, createOrder } from '../stores/orders.js';
import { getBurnRate, suggestedReorderPoint } from './forecasting.js';

// Check all materials and return those needing reorder
export function detectReorderNeeded() {
  const materials = getAllMaterials();
  const activeOrders = getActiveOrders();

  // Build set of materialIds that already have active POs
  const pendingMaterialIds = new Set();
  for (const order of activeOrders) {
    for (const li of order.lineItems) {
      pendingMaterialIds.add(li.materialId);
    }
  }

  const needsReorder = [];

  for (const mat of materials) {
    // Skip if no supplier linked
    if (!mat.supplierId) continue;
    // Skip if already has an active PO
    if (pendingMaterialIds.has(mat.id)) continue;

    const burnRate = getBurnRate('material', mat.id, 30);
    const leadTime = mat.leadTimeDays || 7;
    const effectiveReorder = mat.reorderPoint || suggestedReorderPoint(burnRate, leadTime) || mat.lowThreshold;

    if (effectiveReorder && mat.quantity <= effectiveReorder) {
      // Calculate suggested order quantity: enough for 2x lead time minus current stock
      const suggestedQty = Math.max(
        mat.moq || 1,
        Math.ceil(burnRate * leadTime * 2) - mat.quantity
      );

      needsReorder.push({
        materialId: mat.id,
        materialName: mat.name,
        supplierId: mat.supplierId,
        currentQty: mat.quantity,
        reorderPoint: effectiveReorder,
        suggestedQty: Math.max(suggestedQty, 1),
        unitCost: mat.costPerUnit || 0,
        unit: mat.unit,
        burnRate,
        leadTimeDays: leadTime,
      });
    }
  }

  return needsReorder;
}

// Group items by supplier and generate draft POs
export async function generatePurchaseOrders(items) {
  const suppliers = getAllSuppliers();
  const grouped = {};

  for (const item of items) {
    if (!grouped[item.supplierId]) grouped[item.supplierId] = [];
    grouped[item.supplierId].push(item);
  }

  const createdOrders = [];

  for (const [supplierId, lineItems] of Object.entries(grouped)) {
    const supplier = suppliers.find(s => s.id === parseInt(supplierId));
    if (!supplier) continue;

    const order = await createOrder({
      supplierId: parseInt(supplierId),
      status: 'draft',
      autoGenerated: true,
      lineItems: lineItems.map(li => ({
        materialId: li.materialId,
        quantity: li.suggestedQty,
        unitCost: li.unitCost,
        receivedQty: 0,
      })),
      expectedDelivery: new Date(Date.now() + (supplier.defaultLeadTimeDays || 7) * 86400000).toISOString(),
    });

    createdOrders.push(order);
  }

  return createdOrders;
}

// Format PO as email body
export function formatPOEmail(order, supplier, materials, businessName) {
  const lineItemsText = order.lineItems.map(li => {
    const mat = materials.find(m => m.id === li.materialId);
    const total = (li.quantity * (li.unitCost || 0)).toFixed(2);
    return `  - ${mat?.name || 'Item'}: ${li.quantity} ${mat?.unit || 'units'} @ $${(li.unitCost || 0).toFixed(2)} = $${total}`;
  }).join('\n');

  return `Purchase Order ${order.poNumber}\nFrom: ${businessName}\nTo: ${supplier.name}\nDate: ${new Date(order.createdAt).toLocaleDateString()}\n${order.expectedDelivery ? `Expected Delivery: ${new Date(order.expectedDelivery).toLocaleDateString()}\n` : ''}\nItems:\n${lineItemsText}\n\nTotal: $${order.totalCost.toFixed(2)}\n\n${order.notes ? `Notes: ${order.notes}\n` : ''}Please confirm receipt of this order.\n\n— ${businessName} Inventory System`;
}
