// Consolidated CRUD API for all data stores
// Routes by query params: ?store=products&action=list|create|update|delete&id=X
//
// All requests require Authorization: Bearer <jwt> header
// RLS automatically enforces tenant isolation via business_id

const { createClient } = require('@supabase/supabase-js');

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY;

// Store name → Postgres table name
const TABLE_MAP = {
  products: 'products',
  materials: 'materials',
  recipes: 'recipes',
  suppliers: 'suppliers',
  orders: 'purchase_orders',
  purchaseOrders: 'purchase_orders',
  batches: 'batches',
  production: 'production_runs',
  productionRuns: 'production_runs',
  waste: 'waste',
  locations: 'locations',
  history: 'history',
  expenses: 'expenses',
  transactions: 'transactions',
  settings: 'settings',
  photos: 'photos',
  businesses: 'businesses',
  customers: 'customers',
  sales: 'sales_orders',
  salesOrders: 'sales_orders',
  team: 'team_members',
  teamMembers: 'team_members',
};

// camelCase → snake_case field mapping per store
const FIELD_MAPS = {
  products: { needsMade: 'needs_made', inProduction: 'in_production', lowThreshold: 'low_threshold', photoId: 'photo_id', recipeId: 'recipe_id', locationId: 'location_id', customFields: 'custom_fields', costOverride: 'cost_override', sellPrice: 'sell_price', createdAt: 'created_at', updatedAt: 'updated_at' },
  materials: { lowThreshold: 'low_threshold', costPerUnit: 'cost_per_unit', supplierId: 'supplier_id', locationId: 'location_id', reorderPoint: 'reorder_point', leadTimeDays: 'lead_time_days', customFields: 'custom_fields', createdAt: 'created_at', updatedAt: 'updated_at' },
  recipes: { productId: 'product_id', yieldQty: 'yield_qty', createdAt: 'created_at', updatedAt: 'updated_at' },
  suppliers: { contactName: 'contact_name', defaultLeadTimeDays: 'default_lead_time_days', createdAt: 'created_at', updatedAt: 'updated_at' },
  orders: { poNumber: 'po_number', supplierId: 'supplier_id', lineItems: 'line_items', totalCost: 'total_cost', sentAt: 'sent_at', expectedDelivery: 'expected_delivery', receivedAt: 'received_at', approvedBy: 'approved_by', autoGenerated: 'auto_generated', createdAt: 'created_at', updatedAt: 'updated_at' },
  purchaseOrders: { poNumber: 'po_number', supplierId: 'supplier_id', lineItems: 'line_items', totalCost: 'total_cost', sentAt: 'sent_at', expectedDelivery: 'expected_delivery', receivedAt: 'received_at', approvedBy: 'approved_by', autoGenerated: 'auto_generated', createdAt: 'created_at', updatedAt: 'updated_at' },
  batches: { materialId: 'material_id', supplierId: 'supplier_id', purchaseOrderId: 'purchase_order_id', lotNumber: 'lot_number', remainingQty: 'remaining_qty', costPerUnit: 'cost_per_unit', receivedDate: 'received_date', expirationDate: 'expiration_date', createdAt: 'created_at' },
  production: { productId: 'product_id', recipeId: 'recipe_id', batchesUsed: 'batches_used', createdAt: 'created_at' },
  productionRuns: { productId: 'product_id', recipeId: 'recipe_id', batchesUsed: 'batches_used', createdAt: 'created_at' },
  waste: { itemType: 'item_type', itemId: 'item_id', costImpact: 'cost_impact', createdAt: 'created_at' },
  locations: { isDefault: 'is_default', createdAt: 'created_at' },
  history: { itemType: 'item_type', itemId: 'item_id', itemName: 'item_name', changeType: 'change_type', quantityChange: 'quantity_change', newQuantity: 'new_quantity', locationId: 'location_id', createdAt: 'created_at' },
  expenses: { costType: 'cost_type', variableBasis: 'variable_basis', variableRate: 'variable_rate', linkedProductId: 'linked_product_id', createdAt: 'created_at', updatedAt: 'updated_at' },
  transactions: { productId: 'product_id', externalId: 'external_id', createdAt: 'created_at', updatedAt: 'updated_at' },
  customers: { totalSpent: 'total_spent', orderCount: 'order_count', createdAt: 'created_at', updatedAt: 'updated_at' },
  sales: { orderNumber: 'order_number', customerId: 'customer_id', lineItems: 'line_items', shippingCost: 'shipping_cost', shippingAddress: 'shipping_address', trackingNumber: 'tracking_number', paidAt: 'paid_at', shippedAt: 'shipped_at', deliveredAt: 'delivered_at', createdAt: 'created_at', updatedAt: 'updated_at' },
  salesOrders: { orderNumber: 'order_number', customerId: 'customer_id', lineItems: 'line_items', shippingCost: 'shipping_cost', shippingAddress: 'shipping_address', trackingNumber: 'tracking_number', paidAt: 'paid_at', shippedAt: 'shipped_at', deliveredAt: 'delivered_at', createdAt: 'created_at', updatedAt: 'updated_at' },
  team: { userId: 'user_id', invitedBy: 'invited_by', invitedAt: 'invited_at', acceptedAt: 'accepted_at', createdAt: 'created_at' },
  teamMembers: { userId: 'user_id', invitedBy: 'invited_by', invitedAt: 'invited_at', acceptedAt: 'accepted_at', createdAt: 'created_at' },
};

// Convert camelCase record to snake_case for Postgres
function toSnake(storeName, record) {
  const map = FIELD_MAPS[storeName] || {};
  const result = {};
  for (const [key, value] of Object.entries(record)) {
    if (key === 'id') { result.id = value; continue; }
    result[map[key] || key] = value;
  }
  return result;
}

// Convert snake_case record back to camelCase for frontend
function toCamel(storeName, record) {
  const map = FIELD_MAPS[storeName] || {};
  // Build reverse map
  const reverseMap = {};
  for (const [camel, snake] of Object.entries(map)) {
    reverseMap[snake] = camel;
  }
  const result = {};
  for (const [key, value] of Object.entries(record)) {
    if (key === 'business_id') continue; // Don't send business_id to client
    result[reverseMap[key] || key] = value;
  }
  return result;
}

function createUserClient(token) {
  return createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${token}` } },
  });
}

module.exports = async (req, res) => {
  // Extract auth token
  const authHeader = req.headers.authorization;
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    return res.status(401).json({ error: 'Unauthorized' });
  }
  const token = authHeader.split(' ')[1];
  const supabase = createUserClient(token);

  // Verify user
  const { data: { user }, error: authError } = await supabase.auth.getUser();
  if (authError || !user) {
    return res.status(401).json({ error: 'Invalid token' });
  }

  const store = req.query.store;
  const action = req.query.action || (req.method === 'GET' ? 'list' : 'create');
  const recordId = req.query.id ? parseInt(req.query.id) : null;

  const tableName = TABLE_MAP[store];
  if (!tableName) {
    return res.status(400).json({ error: `Unknown store: ${store}` });
  }

  try {
    // ── GET BUSINESS ID ──
    const { data: biz } = await supabase.from('businesses').select('id').single();
    if (!biz) return res.status(403).json({ error: 'No business profile' });
    const businessId = biz.id;

    switch (action) {
      // ── LIST (GET all records) ──
      case 'list': {
        const { data, error } = await supabase
          .from(tableName)
          .select('*')
          .order('created_at', { ascending: false });

        if (error) throw error;
        return res.status(200).json(data.map(r => toCamel(store, r)));
      }

      // ── GET ONE ──
      case 'get': {
        if (!recordId) return res.status(400).json({ error: 'Missing id' });
        const { data, error } = await supabase
          .from(tableName)
          .select('*')
          .eq('id', recordId)
          .single();

        if (error) throw error;
        return res.status(200).json(toCamel(store, data));
      }

      // ── CREATE ──
      case 'create': {
        const record = toSnake(store, req.body);
        record.business_id = businessId;
        delete record.id; // Let Postgres auto-generate

        const { data, error } = await supabase
          .from(tableName)
          .insert(record)
          .select()
          .single();

        if (error) throw error;
        return res.status(201).json(toCamel(store, data));
      }

      // ── UPDATE ──
      case 'update': {
        if (!recordId) return res.status(400).json({ error: 'Missing id' });
        const updates = toSnake(store, req.body);
        delete updates.id;
        delete updates.business_id;
        updates.updated_at = new Date().toISOString();

        const { data, error } = await supabase
          .from(tableName)
          .update(updates)
          .eq('id', recordId)
          .select()
          .single();

        if (error) throw error;
        return res.status(200).json(toCamel(store, data));
      }

      // ── DELETE ──
      case 'delete': {
        if (!recordId) return res.status(400).json({ error: 'Missing id' });
        const { error } = await supabase
          .from(tableName)
          .delete()
          .eq('id', recordId);

        if (error) throw error;
        return res.status(200).json({ success: true, id: recordId });
      }

      // ── UPSERT (for settings) ──
      case 'upsert': {
        const record = toSnake(store, req.body);
        record.business_id = businessId;

        const { data, error } = await supabase
          .from(tableName)
          .upsert(record, { onConflict: 'business_id,key' })
          .select()
          .single();

        if (error) throw error;
        return res.status(200).json(toCamel(store, data));
      }

      // ── BATCH CREATE ──
      case 'batch': {
        const records = req.body.records || [];
        const mapped = records.map(r => {
          const rec = toSnake(store, r);
          rec.business_id = businessId;
          delete rec.id;
          return rec;
        });

        const { data, error } = await supabase
          .from(tableName)
          .insert(mapped)
          .select();

        if (error) throw error;
        return res.status(201).json(data.map(r => toCamel(store, r)));
      }

      // ── PROFILE (special: get/update business profile) ──
      case 'profile': {
        if (req.method === 'GET') {
          const { data, error } = await supabase
            .from('businesses')
            .select('*')
            .single();
          if (error) throw error;
          return res.status(200).json(toCamel('businesses', data));
        } else {
          const updates = req.body;
          const { data, error } = await supabase
            .from('businesses')
            .update(updates)
            .eq('id', businessId)
            .select()
            .single();
          if (error) throw error;
          return res.status(200).json(toCamel('businesses', data));
        }
      }

      default:
        return res.status(400).json({ error: `Unknown action: ${action}` });
    }
  } catch (error) {
    console.error(`Data API error [${store}/${action}]:`, error.message);
    return res.status(500).json({ error: error.message });
  }
};
