// POST /api/migrate
// Imports IndexedDB export data into Supabase Postgres for the authenticated user.
// Maps camelCase JS fields to snake_case Postgres columns.
// Handles foreign key remapping (old auto-increment IDs → new Postgres IDs).

const { authenticate, getServiceClient } = require('./_lib/auth');

// Field mapping: IndexedDB camelCase → Postgres snake_case
const FIELD_MAPS = {
  products: {
    needsMade: 'needs_made', inProduction: 'in_production', lowThreshold: 'low_threshold',
    photoId: 'photo_id', recipeId: 'recipe_id', locationId: 'location_id',
    customFields: 'custom_fields', costOverride: 'cost_override', sellPrice: 'sell_price',
    createdAt: 'created_at', updatedAt: 'updated_at',
  },
  materials: {
    lowThreshold: 'low_threshold', costPerUnit: 'cost_per_unit', supplierId: 'supplier_id',
    locationId: 'location_id', reorderPoint: 'reorder_point', leadTimeDays: 'lead_time_days',
    customFields: 'custom_fields', createdAt: 'created_at', updatedAt: 'updated_at',
  },
  recipes: {
    productId: 'product_id', yieldQty: 'yield_qty',
    createdAt: 'created_at', updatedAt: 'updated_at',
  },
  suppliers: {
    contactName: 'contact_name', defaultLeadTimeDays: 'default_lead_time_days',
    createdAt: 'created_at', updatedAt: 'updated_at',
  },
  purchaseOrders: {
    poNumber: 'po_number', supplierId: 'supplier_id', lineItems: 'line_items',
    totalCost: 'total_cost', sentAt: 'sent_at', expectedDelivery: 'expected_delivery',
    receivedAt: 'received_at', approvedBy: 'approved_by', autoGenerated: 'auto_generated',
    createdAt: 'created_at', updatedAt: 'updated_at',
  },
  batches: {
    materialId: 'material_id', supplierId: 'supplier_id', purchaseOrderId: 'purchase_order_id',
    lotNumber: 'lot_number', remainingQty: 'remaining_qty', costPerUnit: 'cost_per_unit',
    receivedDate: 'received_date', expirationDate: 'expiration_date',
    createdAt: 'created_at',
  },
  productionRuns: {
    productId: 'product_id', recipeId: 'recipe_id', batchesUsed: 'batches_used',
    createdAt: 'created_at',
  },
  waste: {
    itemType: 'item_type', itemId: 'item_id', costImpact: 'cost_impact',
    createdAt: 'created_at',
  },
  locations: {
    isDefault: 'is_default', createdAt: 'created_at',
  },
  history: {
    itemType: 'item_type', itemId: 'item_id', itemName: 'item_name',
    changeType: 'change_type', quantityChange: 'quantity_change', newQuantity: 'new_quantity',
    locationId: 'location_id', createdAt: 'created_at',
  },
  expenses: {
    costType: 'cost_type', variableBasis: 'variable_basis', variableRate: 'variable_rate',
    linkedProductId: 'linked_product_id', createdAt: 'created_at', updatedAt: 'updated_at',
  },
  transactions: {
    productId: 'product_id', externalId: 'external_id',
    createdAt: 'created_at', updatedAt: 'updated_at',
  },
};

// IndexedDB store name → Postgres table name
const TABLE_MAP = {
  products: 'products',
  materials: 'materials',
  recipes: 'recipes',
  suppliers: 'suppliers',
  purchaseOrders: 'purchase_orders',
  batches: 'batches',
  productionRuns: 'production_runs',
  waste: 'waste',
  locations: 'locations',
  history: 'history',
  expenses: 'expenses',
  transactions: 'transactions',
  settings: 'settings',
};

function mapRecord(storeName, record, businessId) {
  const fieldMap = FIELD_MAPS[storeName] || {};
  const mapped = { business_id: businessId };

  for (const [key, value] of Object.entries(record)) {
    if (key === 'id') continue; // Skip old auto-increment IDs
    const pgKey = fieldMap[key] || key;
    mapped[pgKey] = value;
  }

  return mapped;
}

module.exports = async (req, res) => {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { userId, businessId } = await authenticate(req);
    const { data: exportData } = req.body;

    if (!exportData) {
      return res.status(400).json({ error: 'Missing data in request body' });
    }

    const supabase = getServiceClient();
    const results = {};
    const idMaps = {}; // { storeName: { oldId: newId } }

    // Import order matters for foreign keys
    const importOrder = [
      'suppliers', 'locations', 'products', 'materials', 'recipes',
      'purchaseOrders', 'batches', 'productionRuns', 'waste',
      'history', 'expenses', 'transactions', 'settings',
    ];

    for (const storeName of importOrder) {
      const records = exportData[storeName];
      if (!records || !records.length) {
        results[storeName] = 0;
        continue;
      }

      const tableName = TABLE_MAP[storeName];
      if (!tableName) continue;

      // Special handling for settings (key-value store)
      if (storeName === 'settings') {
        for (const rec of records) {
          const { error } = await supabase.from('settings').upsert({
            business_id: businessId,
            key: rec.key,
            value: rec.value != null ? JSON.stringify(rec.value) : null,
          }, { onConflict: 'business_id,key' });
          if (error) console.warn('Settings import error:', error.message);
        }
        results[storeName] = records.length;
        continue;
      }

      // Map all records
      const mapped = records.map(r => mapRecord(storeName, r, businessId));

      // Insert and get back IDs for FK remapping
      const { data: inserted, error } = await supabase
        .from(tableName)
        .insert(mapped)
        .select('id');

      if (error) {
        console.error(`Error importing ${storeName}:`, error.message);
        results[storeName] = { error: error.message };
        continue;
      }

      // Build ID map (old position-based → new Postgres ID)
      idMaps[storeName] = {};
      records.forEach((original, i) => {
        if (inserted[i]) {
          idMaps[storeName][original.id] = inserted[i].id;
        }
      });

      results[storeName] = inserted.length;
    }

    return res.status(200).json({
      success: true,
      imported: results,
      message: 'Data migration complete',
    });
  } catch (error) {
    console.error('Migration error:', error.message);
    const status = error.status || 500;
    return res.status(status).json({ error: error.message });
  }
};
